name: is_airplane_mode
description: "Checks if the device is in airplane mode on Android and iOS"
version: 0.0.1
homepage: https://github.com/curiouslumber/is_airplane_mode

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.noelpinto.is_airplane_mode
        pluginClass: IsAirplaneModePlugin
      ios:
        pluginClass: IsAirplaneModePlugin